<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FFMpegCore" Version="5.4.0" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260427" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.13.0.20260427" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260302" />
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
    <PackageReference Include="SkiaSharp.Views.Desktop.Common" Version="3.119.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NsfwSharp-main\NsfwSharp-main\NsfwSharp\NsfwSharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="erax_nsfw_yolo11m.onnx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="SFWCensor.onnx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="YOLO26SFW.onnx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="YOLO26SFWV2.onnx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="yolov8s-pose.onnx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="yolo_11m_nsfw.onnx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>